# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

services:
  - docker:dind

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - yarn install 
    - yarn workspaces run build

test:
  stage: test
  script:
    - yarn workspaces run test

package:
  stage: package
  script:
    - yarn workspaces run package
