language: node_js
node_js:
  - 12
script:
  - yarn install
  - yarn workspaces run build
  - yarn workspaces run test

deploy:
  provider: script
  script: yarn workspaces run package
  on:
    branch: master
